name: test_involve
description: test_involve

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 3.24.0
  get_storage: 1.4.0
  dio: ^3.0.8
  cupertino_icons: ^1.0.0
  global_configuration: ^1.6.0
  json_annotation: any
  build_runner: any
  json_serializable: any
  json_model: any
  flutter_svg: any
  flutter_map: any
  latlng: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/cfg/

